BLACKLIST = set([
'1970 acm turing lecture',
'1st ed.',
'1st edition',
'10-year award',
'2nd ed.',
'3rd edition',
'abridged version',
'abstract',
'abstract of invited tutorial',
'abstract only',
'abstracts',
"acm president's letter",
'addison-wesley professional ruby series',
'a. m. turing award lecture',
'an announcement',
'an extended abstract',
'a preliminary version',
'a research proposal',
'avstract',
'awarded best paper!',
'awarded best paper',
'awarded best student paper!',
'awarded best student paper',
'best paper',
'brief announcement',
'brief announement',
'da/ms/ss',
'demo',
'demonstration description',
'demonstration paper',
'detailed abstract',
'draft',
"editor's introduction",
'experience paper',
'extenced abstract',
'extended abstract',
'extended abstracts',
'extended announcement',
'extended anstract',
'extended astract',
'extended summary',
'extended version',
"guest editor's introduction",
"guest editors' introduction",
"guest editors' intruduction",
'indroduction to the special section on logic programming',
'interview',
'introduction to the special issue',
'introduction to the special section',
'intruduction to the special section',
'invited address',
'invited paper',
'invited talk',
'invited industrial talk',
'industrial session',
'keynote',
'keynote address',
'microsoft windows server system series',
'panel',
'panel abstract',
'panel session, abstract only',
'panel session - title only',
'panel session, title only',
'panel statement',
'partial report',
'pearl',
'podc 1984 invited address',
'poster',
'poster abstract',
'preliminary abstract',
'preliminary draught',
'preliminary draft',
'preliminary report',
'preliminary reports',
'preliminary version',
'prentice hall open source software development series',
'proceedings',
'remarks',
'report of the jtec panel',
'reprint',
'second edition',
'short abstract',
'short paper',
'shortened version',
'sintra, portugal, 7-10 september 1998',
'summary',
"surveyors' forum",
'tdgs',
'turing award lecture',
'tutorial',
'working paper',
'work in progress, abstract',
'wii',
'version 2.0',
])

WHITELIST = set([
'!=',
'?',
'0, 1',
'1',
'1, 2',
'1, 342 times and counting',
'1600 cpi, phase encoded',
'1923 - 2008',
'1925-2008',
'1926-2008',
'1956-2005',
'1972-2006',
'1976-1978',
'1988-1991',
'1982',
'1993',
'1 + beta',
'1 + eps',
'1 + epsilon',
'1+, varepsilon;, beta',
'2 + epsilon',
'2+epsilon',
'5/3 + ε',
'2k',
'32x40 gbit/s',
'800 cpi, nrzi',
'802.6',
'9 track-200 and 800 cpi, nrzi and 1600 cpi, p.e.',
'a case of error reporting system',
'acsii',
'active suspension',
'acyclic',
'advances in information security',
'a fictional case study',
'aims',
'asap',
'aims-2',
'aims-3',
'algorithm a433',
'algorithm a438',
'almost',
'alpha, beta',
'and a letter',
'and an app store',
'and beyond?',
'and beyond',
'and commit',
'and dark energy',
'and darwinian',
'and some unknown',
'and everthing in between',
'and everything else',
'and future',
'and how flash memory changes the rules',
'and how not',
'and how not to',
"and how they're sometimes found",
'and mistrust',
'and other',
'and others too!',
'and pretty good for quantum as well',
'and safety',
'and the sesame street syndrome',
'and trusting no one',
'a timely approach',
'a polynomial algorithm for 3-compatible colouring and the stubborn list partition problem',
'applications of comparative physical maps in molecular evolution',
'april 1984 special section',
'are not',
'arik, m. and akan, o.b.',
'a state-of-the-art report on omg/corba',
'a usaai',
"avocs'14",
'beta,gamma,delta',
'biastm',
'bpm',
'bold',
'bsr',
'btx',
'bus',
'but we all see the point of tainting',
"but don't currently",
'but might have been afraid to ask',
'byzantine agreement on uniformly random values',
'cam',
'causal',
'cbids',
'c-fd3r mac',
'class hierarchical open interface for custom embedded systems',
'commerce edition',
'components + patterns',
'computer',
'computer communications and networks',
'conference report: compcon 96',
'connected',
'connectionless',
'console operator proficiency examination',
"cop's",
'cogs',
'cosers',
'cost',
'cloudb 2010',
'closed',
'creation and use',
'csma/ri',
'cycles, and partitions',
'cyber',
'coda',
'd3',
'd2d',
'data',
'database',
'dctcp',
'de',
'delta+1',
'duality',
'deadlock detection',
'delta + o(delta)',
'demo abstract',
'de-sco',
'deterministic',
'dft-msns',
'dir',
'distributed',
'dis',
'disco',
'd, k',
'double soft decision',
'dsdv',
'dynamic',
'e-',
'early and often?',
'else',
'epsilon, delta',
'esair',
'est',
'even and odd orders',
'even order',
'expected time',
'fairly',
'fdna-03',
'febid 2010',
'ferrite',
'+-f(+-f(...+-f(x)...))',
'fitting distances by tree metrics',
'fiwi',
'flow',
'for high-concurrency servers',
'for vlsi',
'fqse',
'ftscs 2014',
'gier algol',
'googling the internet',
'gradually',
'great!',
'h-015',
'hdsl and adsl',
'h-k',
'hms',
'hopefully',
"hotpower'11",
"hotswup'09",
"hotswup'11",
'hubs',
'hyper',
"ifip/sec'84 proceedings",
"ifip/sec'85 proceedings",
'ii',
'iir',
'im',
'in',
'in cournot competition',
'incremental',
'indeterministic',
'information pollution',
'in capes!',
'in java',
'in networking',
'inter-',
'intermittent assertions in proving program correctness',
'internals overview',
'intervals',
'isap',
'jsq',
'june 1962',
'<= k',
'k <= 6',
'k, r',
'k, n',
'ladis 2009',
'ladis 2011',
'lbc',
'ldl',
'ldl1',
'lis4d',
'learning a string',
'leveled',
'lms',
'log ^c n',
'log c n',
'log n',
"maier's o-logic revisited",
'mar/apr 08 26-32',
'managing information domains as political economies',
'max, min',
'maybe',
'motifs',
'mdgs',
'meta',
'meta-',
'milman',
'mis',
'mlr',
'm&m',
'mod p - mod m',
'more',
'mtit',
'mud',
'multi',
'multimesh',
'natural',
'n, d',
'nearly',
'nemo',
'netdb 2009',
'nextgen',
'networks of workstations',
'nicta',
'n log n',
'non-',
'non',
'non-uniform message-passing',
"nossdav '93",
'not',
'not a privilege',
'not so',
'ns32532',
'n, t',
'object database and environment',
'odd and even orders',
'odd and, even orders',
'odd order',
'oetc',
'of communications',
'often',
'ofdma-pon',
'on behalf of john cocke',
'online',
'only',
"opensig'98",
'opsinet',
'open',
'optimal',
'oracle curve plotter',
'or, business processes for database researchers',
'or half-truths',
'or how to turn ideas into live systems in a breeze',
'or not',
'or, programs from outer space',
'or repetitive consensus',
'or, routing issues in mpls',
'or towards a standard ada subset',
'or vice versa',
'or why capabilities might have been invented',
'or, why mazes are easier to search than graphs',
'output',
'o(n)',
'over',
'p2p',
'parallel',
'part 1',
'part 2',
'part i',
'part ii',
'part i: the architecture',
'pc-smz',
'physical design tuning',
'poly',
'polynomial algorithm for genomic distance problem',
'position paper',
'public key infrastructure',
'plain',
'p, q',
'priority queue',
'probably',
"proc. sigmod'03",
'proposed',
'physical',
'psa',
'psbgp',
'qpr-tcm',
'qspnet',
'rad-mud',
'ra-dsl',
'raid',
'rdkm',
're',
'really',
'rectangular matrices',
'remark on algorithms 352, 385, 392',
'repeated',
'rfcs',
'rladsms',
'rohc',
'rome',
'rwa',
'ring-',
's',
'scam 2013',
'satnet',
'sba',
's-bgp',
'sdd-1',
'secret',
'sembegs',
'scalable and expressive packet classification',
'semi',
'sharqfec',
'shielded',
'software',
'some',
'some preprocessing required',
"sosp'99",
'sigcomm',
'source',
'speed08',
's.p.m',
'spo protocol',
's, t',
'stack',
'sites',
'standard',
'storage',
'stream-enabled',
'sparse',
'sundr',
'systor 2007',
'switzerland/germany',
'results on current cycling experiments on des',
't + 1',
'tase 2016',
'talking with julian gosper, jean-luc agathos, richard rutter, and terry coatta',
'the choice of decimal or binary representation',
'the odds are on his side',
'the open channel',
'the vasa',
'thm'
'travelocity-based detouring',
'tribute, jonathan b. postel 1943-1998',
'turbo',
'threshold schemes',
'tweakable',
'1935-2007',
'1+epsilon',
'1+\u03ad',
'1 + \u03b5',
'un',
'unproven',
'unto',
'unweighted',
'o, \u03ba',
'ural',
'ussr',
'very',
'viewpoint',
'vlsi',
'wavelength',
'weakly',
'wep',
'what is the info age?',
'what once was',
'what time will you die?',
'where will the brain power come from?',
'why id might not be strict',
'wie2009',
'wie2011',
'wit',
'without conditional statements',
'without it even noticing',
'without matrix multiplication',
'without powerdomains',
'with retrospective',
'workshop rewiew',
'worm',
'wyxiwyg',
'x',
'x.1500',
'xquery by example',
])

TRANSLATE = {
    'ISDN, panel': 'ISDN',
}
